//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationQLSV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SinhVien
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Bắt Buộc !!!")]
        public string MaSV { get; set; }
        [Required(ErrorMessage = "Bắt Buộc !!!")]
        public string TenSV { get; set; }
        [Required(ErrorMessage = "Bắt Buộc !!!")]
        public string Lop { get; set; }
        [Required(ErrorMessage = "Bắt Buộc !!!")]
        public string GioiTinh { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public string QueQuan { get; set; }
        public string DanToc { get; set; }
    }
}
